version: "3"

services:
  my-app:
    # image: cr.yandex/crp11e63ns0rgi2120do/myapp:latest
    platform: linux/amd64
    build:
      context: .
    # depends_on:
    #   - postgres
    environment:
      # DATABASE_URL: postgres://postgres:newPassword@postgres:5432/my-db-name
      NODE_ENV: ${NODE_ENV:-development}
      PORT: ${PORT:-3000}
      env_file:
        .env
    ports:
      - "${PORT:-3000}:3000"
    restart: always
    networks:
      - awesome

  # nginx:
  #   image: nginx
  #   restart: always
  #   #container_name: nginx
  #   volumes:
  #     - ./docker/nginx/certs:/etc/nginx/certs
  #     - ./docker/nginx/core:/etc/nginx/conf.d
  #     - ./docker/nginx/logs/:/var/log/nginx/
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "443:443"
  #   networks:
  #     - awesome

networks:
  awesome:
    driver: bridge